services:
  app:
    build: 
      context: .
    container_name: distributedsystems
    ports:
      - "3000:3000" 
    restart: unless-stopped
    environment:
      PORT: ${PORT:-3000} 
      MONGODB_URL: ${MONGODB_URL:-mongodb://mongodb:27017/mongo-distributedsystems} 
      REDIS_HOST: ${REDIS_HOST:-redis} 
      REDIS_PORT: ${REDIS_PORT:-6379} 
      CACHE_TTL: ${CACHE_TTL:-60}
      TRAFFIC_DISTRIBUTION_TYPES: ${TRAFFIC_DISTRIBUTION_TYPES:-poisson,uniforme} 
    depends_on:
      - mongodb 
      - redis  
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 
    command: npm run start:dev  
  
  # Servicio MongoDB
  mongodb:
    image: mongo:5 
    container_name: mongo-distributedsystems
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 
    restart: always 

  # Servicio Redis
  redis:
    image: redis:latest 
    container_name: redis-distributedsystems
    ports:
      - "6379:6379"
    restart: always 
    ### Politicas de remocion y tamaño de cache, descomentar la politica a utilizar y comentar TODAS las demas (Cambian tamaño de cache a gusto): 
    ## Politica de remocion LRU
    # command: redis-server --save "" --appendonly no --maxmemory 256mb --maxmemory-policy allkeys-lru
    ## Politica de remocion LFU
    command: redis-server --save "" --appendonly no --maxmemory 8mb --maxmemory-policy allkeys-lfu
    
  
volumes:
  mongo_data: